export const data = [
    { id: 1,color:"bg-red-700", name: "React", image: "/image/react.jpg", description: "React is a JavaScript library developed by Facebook for building user interfaces. It allows developers to create reusable UI components, manage application state, and efficiently update the user interface when data changes. React uses a virtual DOM to optimize rendering performance, making it particularly well-suited for building fast and responsive web applications. It supports component-based architecture, making code more modular and easier to maintain. With features like hooks for managing state and side effects, React simplifies complex UI development tasks. It's widely used for both web and mobile applications, thanks to its flexibility and robust ecosystem." },
    { id: 2,color:"bg-red-700", name: "Express", image: "/image/express1.png", description: "Discover the power of Express.js, a lightweight and flexible JavaScript framework for building high-performance web applications. With its robust routing system, extensibility, and support for server-side rendering, Express.js offers simplicity and efficiency, making it the preferred choice for developers. Explore how Express.js can enhance your web development projects today!" },
    { id: 3,color:"bg-red-700", name: "Next js", image: "/image/next.webp", description: "Next.js is a React framework that enables server-side rendering and static site generation, enhancing performance and SEO. It offers built-in routing, API routes, and optimized image handling. Ideal for developing fast, scalable web applications, it simplifies tasks like code splitting, hot reloading, and server-side data fetching." },
    { id: 4,color:"bg-red-700", name: "Mongodb", image: "/image/mongodb.svg", description: "Discover the power of MongoDB development with SoftLab IT. Our SEO-friendly services harness the capabilities of this flexible NoSQL database, enabling businesses to build scalable and high-performance data-driven applications. Explore why MongoDB is the preferred choice for modern data storage and unlock the full potential of your projects" },
    { id: 5,color:"bg-red-700", name: "Node js", image: "/image/node.webp", description: "Discover the power of Node.js development with SoftLab IT. Our SEO-friendly services harness the capabilities of this efficient JavaScript runtime, empowering businesses with scalable and high-performance web applications. Explore why Node.js is the preferred choice for building modern server-side applications and unlock the full potential of your projects." },
    { id: 6,color:"bg-red-700", name: "TypeScript", image: "/image/ts.webp", description: "TypeScript is a superset of JavaScript that adds optional static typing and other features to improve the development experience. It is designed to help developers catch errors early and improve code maintainability." },

] 
